### ISSUE TITLE
vrt compatibility

### ISSUE THREAD

**Issue by nferruzzi** [ecometrica/gdal2mbtiles#29] opened 2019-08-07 11:02 UTC
Hi, my input file is a vrt composed of thoundands of tif files with /vsitar/ and /vsizip/ paths. Any chance to have it supported ? alternatevely,  do you know any workaround without rendering it to a huge intermediate tiff file ? thanks in advance

**Comment by pauricthelodger** [comment] 2019-08-09 10:52
Hey @nferruzzi,

Thanks for the question, we're looking into it at the minute. Could you upload an example for a file so we can test/reproduce? Maybe not one with thousands though? ;)

Cheers!

**Comment by pauricthelodger** [comment] 2019-08-09 10:54
Oh, as part of that, could you also upload the cli output for the command and error you get when trying to run the example file? Thanks!

**Comment by nferruzzi** [comment] 2019-08-09 11:19
Hi thanks for looking at this.

I've just realized on my attempt to reproduce that `gdal2mbtiles` accept a direct ".vrt" file  but it is not happy with one referince another vrt file

```
13:08 $ gdalinfo --version
GDAL 2.4.2, released 2019/06/28

13:09 $ gdal2mbtiles -v N000E005_N005E010_R_3857.vrt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/gdal2mbtiles", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/main.py", line 309, in main
    colors=colors, band=band)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/helpers.py", line 211, in warp_mbtiles
    pngdata=pngdata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/helpers.py", line 73, in image_mbtiles
    pyramid = preprocessor(**locals())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/helpers.py", line 324, in resample_after_warp
    pyramid.dataset.resample(resolution=resolution)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/vips.py", line 601, in resample
    ratios=self.GetScalingRatios(resolution=resolution, places=5)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/vips.py", line 580, in _resample
    self._image = VImageAdapter(self.image).stretch(
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gdal2mbtiles/vips.py", line 518, in image
    self._image = Image.new_from_file(self.inputfile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyvips/vimage.py", line 217, in new_from_file
    raise Error('unable to load from file {0}'.format(vips_filename))
pyvips.error.Error: unable to load from file b'N000E005_N005E010_R_3857.vrt'
  VipsForeignLoad: "N000E005_N005E010_R_3857.vrt" is not a known file format
```

All files are in the attachment 
[Archive.zip](https://github.com/ecometrica/gdal2mbtiles/files/3486077/Archive.zip)

Steps to reproduce:
1. create the initial vrt file with : `gdalbuildvrt -input_file_list files.txt N000E005_N005E010_R.vrt`
1. warp it with `gdalwarp -t_srs EPSG:3857 -r bilinear N000E005_N005E010_R.vrt N000E005_N005E010_R_3857.vrt` probably I don't need this one for `gdal2mbtiles` to work but I've other warp parameters in the complete workflow so I still need to support a multi step vrt
1. execute `gdal2mbtiles -v N000E005_N005E010_R_3857.vrt`

thanks in advance

**Comment by elfmanryan** [comment] 2019-08-09 12:01
Could you try passing it the single level vrt, and letting gdal2mbtiles do the warp internally (GDAL warp arguments:
  --spatial-reference SPATIAL_REFERENCE
                        Destination EPSG spatial reference. Defaults to 3857) . I think what is happening is that because you are passing a vrt that is in 3857, it passes the checks and goes to pyvips, which cant handle a vrt.

**Comment by nferruzzi** [comment] 2019-08-09 12:39
actually it works, and it works with multiple steps vrt too all I've to to is to remove the spatial reference warping and keeping other parms (like a resizing with gdalwarp -ts 1000 0) ... at the moment I think this bug can be closed :) ..

**Comment by elfmanryan** [comment] 2019-08-09 12:42
Sorry edited my comment, but yes that makes sense then, it doesnt matter how man nested vrts there are, because if a warping is done by gdal2mbtiles to get to 3857, gdal will read it and create the required tifs

**Comment by nferruzzi** [comment] 2019-08-09 12:43
ok sorry one last question: so does it mean that gdal behind the scene is generating a huge tif file ? because I've earth size tiff XD and that is not going to work .. for instance with the same vrt (+ the spatial warping) gdal2tiles does not create any intermediate file

**Comment by elfmanryan** [comment] 2019-08-09 14:45
yes i think so, but ill double check

**Comment by nferruzzi** [comment] 2019-08-09 15:38
I've done some short tests, and yes it creates a temp vrt and generates a temp tif file .. so I'm back to square one. It works but is not usable for my case :(
My uncompressed source is circa 0.8TB and a reprojection would be almost the same size, unfortunately I go with ec2 and can't budget a test like this.
Yet, for refence, gdal2tiles manages to "render" just what it needs for a single / chunk of tiles at the base map resolution requested. I guess if this could be a "feature request" for your project which I really hope to use someday :) thanks for all

**Comment by elfmanryan** [comment] 2021-11-03 14:10
Closing this issue as gdal2mbtiles appears to be doing as expected

**Closed by elfmanryan** 2021-11-03 14:10 UTC
